[build]
  base = ""
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify-functions"
  node_version = "18"

[edge_functions]
  directory = "edge-functions"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    # Mejora la seguridad
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "sniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Mejora el rendimiento
    Cache-Control = "public, max-age=0, must-revalidate"
    # Soporte para PWA
    Service-Worker-Allowed = "/"
